# PSP build -> EBOOT.PBP  (needs pspdev: export PSPDEV=~/pspdev; PATH=$PSPDEV/bin:$PATH)
#   make -f Makefile.psp
# then copy build/luftrauser/assets.pak next to EBOOT.PBP on the Memory Stick
# (ms0:/PSP/GAME/LUFTRAUSER/).

TARGET = luftrauser
OBJS = \
  src/fp.o src/entity.o src/world.o src/pak.o src/input.o \
  src/audio_mix.o src/drmp3_impl.o \
  game/game.o game/player.o game/uboot.o game/backdrop.o \
  game/fx.o game/enemy.o game/bullet.o game/brit.o game/jet.o game/sea.o game/text.o \
  platform/psp/gfx_psp.o platform/psp/input_psp.o platform/psp/audio_psp.o \
  platform/psp/main_psp.o

INCDIR   = src .
CFLAGS   = -O2 -G0 -Wall -std=c11 -Wno-unused-parameter
ASFLAGS  = $(CFLAGS)
LDFLAGS  =
LIBS     = -lpspgum -lpspgu -lm -lpspaudiolib -lpspaudio -lpspctrl -lpspdisplay -lpspge -lpspdebug

EXTRA_TARGETS   = EBOOT.PBP
PSP_EBOOT_TITLE = Luftrauser

PSPSDK = $(shell psp-config --pspsdk-path)

all: gen/spec_luftrauser.h

gen/spec_luftrauser.h: ../spec/luftrauser.toml ../spec/gen_spec.py
	../.venv/bin/python ../spec/gen_spec.py

$(OBJS): gen/spec_luftrauser.h

include $(PSPSDK)/lib/build.mak
