#!/usr/bin/env python3
"""Generate runtime/nfm/gen/control_gen.inc — a mechanical Java->C translation of Control.java's AI driver.

Usage: gen_nfm_control.py [path/to/Control.java]   (default: $NFM_SRC/Control.java)
Same line-wise approach as gen_nfm_mad.py.  Math.random() (m.random) becomes ctl_rand(C), a per-driver LCG.
"""
import os
import re
import sys
from pathlib import Path

SIGS = {
    "public void falseo(": "void control_falseo(Control *C, int n) {",
    "public void reset(": "void control_reset(Control *C, CheckPoints *cp, int n) {",
    "public void preform(": "void control_preform(Control *C, Mad *mad, CarObj *o, CheckPoints *cp, Trackers *T) {",
    "public int py(": "static int cpy(int n, int n2, int n3, int n4) {",
    "public int pys(": "static int cpys(int n, int n2, int n3, int n4) {",
}

RULES = [
    (r"\bfinal\s+", ""),
    (r"\b(int|float|boolean)\[\]\[\] (\w+) = new \1\[(\d+)\]\[(\d+)\];", r"\1 \2[\3][\4] = {{0}};"),
    (r"\b(int|float|boolean)\[\] (\w+) = new \1\[(\d+)\];", r"\1 \2[\3] = {0};"),
    (r"\b(int|float)\[\] (\w+) = ", r"\1 *\2 = "),
    (r"\babs(\d*)\b(?!\()", r"nabs\1"),      # Java locals named abs/abs2 shadow C's abs()
    (r"\bboolean\b", "bool"),
    (r"\bMath\.abs\(", "JABS("),
    (r"\bMath\.(sqrt|acos|pow|atan|sin|cos)\(", r"\1("),
    (r"this\.m\.sin\(", "m_sin("),
    (r"this\.m\.cos\(", "m_cos("),
    (r"this\.m\.random\(\)", "ctl_rand(C)"),
    (r"this\.pys\(", "cpys("),
    (r"this\.py\(", "cpy("),
    (r"\bthis\.", "C->"),
    (r"\bcontO\.(x|y|z|xz|xy|zy|wxz|wzy|dist)\b", r"o->in->\1"),
    (r"\btrackers\.", "T->"),
    (r"\bcheckPoints\.", "cp->"),
    (r"\bmad\.cd\.(\w+)\[([^\]]+)\]", r"mad->cd[\2].\1"),
    (r"\bmad\.", "mad->"),
    (r"\bcontO\b", "o"),
]


def translate(lines):
    out = []
    for ln in lines:
        s = ln.rstrip()
        for pat, rep in RULES:
            s = re.sub(pat, rep, s)
        out.append(s)
    return out


def main():
    p = Path(sys.argv[1] if len(sys.argv) > 1 else os.environ["NFM_SRC"] + "/Control.java")
    src = p.read_text().splitlines()
    out = ["/* GENERATED by spec/gen_nfm_control.py from Control.java — do not edit. */"]
    i = 0
    while i < len(src):
        ln = src[i].strip()
        sig = next((k for k in SIGS if ln.startswith(k)), None)
        if sig is None:
            i += 1
            continue
        j = i + 1
        while src[j] != "    }":
            j += 1
        out.append(SIGS[sig])
        out += translate(src[i + 1:j])
        out.append("}\n")
        i = j + 1
    dst = Path(__file__).resolve().parent.parent / "runtime" / "nfm" / "gen" / "control_gen.inc"
    dst.write_text("\n".join(out) + "\n")
    print(dst, len(out), "lines")


if __name__ == "__main__":
    main()
