#!/usr/bin/env python3
"""Generate runtime/nfm/gen/cardefs.h — the 16 stock cars' stats from CarDefine's constructor.

Usage: gen_nfm_cars.py [path/to/CarDefine.java]   (default: $NFM_SRC/CarDefine.java)
Array order is CarDefine's car index (= GameSparker.array2 mesh order, the names[] order).
Values are copied verbatim (floats stay float32 literals) so Mad sees exactly the Java numbers.
"""
import os
import re
import sys
from pathlib import Path

MESH = ["2000tornados", "formula7", "canyenaro", "lescrab", "nimi", "maxrevenge", "leadoxide", "koolkat",
        "drifter", "policecops", "mustang", "king", "audir8", "masheen", "radicalone", "drmonster"]
INT = ["handb", "airc", "turn", "push", "revpush", "lift", "revlift", "powerloss", "flipy", "msquash", "clrad",
       "maxmag", "cclass", "enginsignature"]
FLT = ["airs", "grip", "bounce", "simag", "moment", "comprad", "dammult", "dishandle", "outdam"]


def arrays(src: str) -> dict:
    out = {}
    for m in re.finditer(r"this\.(\w+) = new (?:int|float|String)(?:\[\])+ (\{.*?\});", src):
        out[m.group(1)] = m.group(2)
    return out


def flat(body: str):
    return [x.strip() for x in re.findall(r'"[^"]*"|-?[\d.]+f?', body)]


def main() -> None:
    p = Path(sys.argv[1] if len(sys.argv) > 1 else os.environ["NFM_SRC"] + "/CarDefine.java")
    a = arrays(p.read_text())
    v = {k: flat(a[k])[:16] for k in INT + FLT + ["names"]}
    sw, ac = flat(a["swits"])[:48], flat(a["acelf"])[:48]
    rows = []
    for i in range(16):
        f = ", ".join(v[k][i] for k in FLT)
        n = ", ".join(v[k][i] for k in INT)
        rows.append(f'    {{ "{MESH[i]}", {v["names"][i]}, {{ {", ".join(sw[i*3:i*3+3])} }}, {{ {", ".join(ac[i*3:i*3+3])} }},\n'
                    f'      {f},\n      {n} }},')
    out = Path(__file__).resolve().parent.parent / "runtime" / "nfm" / "gen" / "cardefs.h"
    out.write_text(
        "/* GENERATED by spec/gen_nfm_cars.py from CarDefine.java — do not edit. */\n"
        "typedef struct {\n    const char *mesh, *name;\n    int swits[3];\n    float acelf[3];\n    float " + ", ".join(FLT) + ";\n"
        "    int " + ", ".join(INT) + ";\n} CarStats;\n"
        "static const CarStats NFM_CARS[16] = {\n" + "\n".join(rows) + "\n};\n")
    print(out)


if __name__ == "__main__":
    main()
