#!/usr/bin/env python3
"""Generate runtime/nfm/gen/ntrig_table.h — Medium.tsin / Medium.tcos.

Medium.java:222-225 fills them as ``(float)Math.cos(i * 0.017453292519943295)`` for
i in 0..359, and all game trig is integer degrees through that table (Medium.sin/cos
wrap by +-360).  Emitting the float32 values as hex-float literals makes the runtime
bit-identical to the original and removes libm trig from the game path entirely,
which is exactly what the PSP's software-double FPU wants.
"""
import math
import struct
from pathlib import Path

DEG = 0.017453292519943295


def f32(x: float) -> float:
    return struct.unpack("<f", struct.pack("<f", x))[0]


def table(fn) -> str:
    rows = []
    for i in range(0, 360, 4):
        rows.append("    " + ", ".join(f32(fn(j * DEG)).hex() + "f" for j in range(i, i + 4)) + ",")
    return "\n".join(rows)


def main() -> None:
    out = Path(__file__).resolve().parent.parent / "runtime" / "nfm" / "gen" / "ntrig_table.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "/* GENERATED by spec/gen_nfm_trig.py — do not edit. Medium.tsin / Medium.tcos. */\n"
        "static const float NTSIN[360] = {\n" + table(math.sin) + "\n};\n"
        "static const float NTCOS[360] = {\n" + table(math.cos) + "\n};\n")
    print(out)


if __name__ == "__main__":
    main()
