#!/usr/bin/env python3
"""Generate runtime/nfm/gen/npieces.h — stage object id -> piece model name.

A stage ``set(id,...)`` refers to ``PIECES[id - PIECE_ID_BASE]`` (pipeline/nfm/tables.py,
GameSparker slot = id + 46).  The runtime resolves the model as ``mesh/piece/<name>``.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from pipeline.nfm.tables import PIECE_ID_BASE, PIECES  # noqa: E402


def main() -> None:
    out = ROOT / "runtime" / "nfm" / "gen" / "npieces.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    body = ",\n".join(f'    "{n}"' for n in PIECES)
    out.write_text(
        "/* GENERATED by spec/gen_nfm_pieces.py — do not edit. */\n"
        f"#define NPIECE_BASE {PIECE_ID_BASE}\n"
        f"#define NPIECE_COUNT {len(PIECES)}\n"
        f"static const char *const NPIECE_NAMES[NPIECE_COUNT] = {{\n{body}\n}};\n")
    print(out)


if __name__ == "__main__":
    main()
