#!/usr/bin/env python3
"""Generate runtime/nfm/gen/mad_gen.inc — a mechanical Java->C translation of Mad.java's physics.

Usage: gen_nfm_mad.py [path/to/Mad.java]   (default: $NFM_SRC/Mad.java)
The decompiled source is one statement per line, so a line-wise rewrite is enough.  Cosmetic calls
(sound, dust/sparks, crash meter, replay recording) become no-op macros defined in runtime/nfm/mad.c;
the Color.getHSBColor damage tinting is dropped.  Everything else keeps Java's operand order and
float/int typing so the port stays bit-comparable to the original.
"""
import os
import re
import sys
from pathlib import Path

SIGS = {
    "public void reseto(": "void mad_reseto(Mad *M, int cn, CarObj *o, CheckPoints *cp) {",
    "public void drive(": "void mad_drive(Mad *M, Control *ctl, CarObj *o, Trackers *T, CheckPoints *cp) {",
    "public void distruct(": "static void mad_distruct(Mad *M, CarObj *o) {",
    "public int regy(": "int mad_regy(Mad *M, int n, float n2, CarObj *o) {",
    "public int regx(": "int mad_regx(Mad *M, int n, float n2, CarObj *o) {",
    "public int regz(": "int mad_regz(Mad *M, int n, float n2, CarObj *o) {",
    "public void colide(": "void mad_colide(Mad *M, CarObj *o, Mad *mad, CarObj *o2) {",
    "public void rot(": "static void rot(float *array, float *array2, int n, int n2, int n3, int n4) {",
    "public int rpy(": "static int rpy(float n, float n2, float n3, float n4, float n5, float n6) {",
    "public int py(": "static int py(int n, int n2, int n3, int n4) {",
}

# (regex, replacement), applied in order to every body line
RULES = [
    (r"\bfinal\s+", ""),
    (r"\babs(\d*)\b(?!\()", r"nabs\1"),      # Java locals named abs/abs2 shadow C's abs()
    (r"\b(int|float|boolean)\[\]\[\] (\w+) = new \1\[(\d+)\]\[(\d+)\];", r"\1 \2[\3][\4] = {{0}};"),
    (r"\b(int|float|boolean)\[\] (\w+) = new \1\[(\d+)\];", r"\1 \2[\3] = {0};"),
    (r"\b(int|float)\[\] (\w+) = ", r"\1 *\2 = "),
    (r"\bboolean\b", "bool"),
    (r"\bPlane (\w+) = (.*);", r"MadPoly *\1 = &\2;"),
    (r"\bplane(\d*)\.", r"plane\1->"),
    (r"\bMath\.abs\(", "JABS("),
    (r"\bMath\.(sqrt|acos|pow|atan|sin|cos)\(", r"\1("),
    (r"this\.m\.sin\(", "m_sin("),
    (r"this\.m\.cos\(", "m_cos("),
    (r"this\.m\.random\(\)", "mad_rand(M)"),
    (r"this\.rot\(", "rot("),
    (r"this\.py\(", "py("),
    (r"this\.rpy\(", "rpy("),
    (r"this\.distruct\(contO\)", "mad_distruct(M, o)"),
    (r"this\.(reg[xyz])\(", r"mad_\1(M, "),
    (r"\bmad\.(reg[xyz])\(", r"mad_\1(mad, "),
    (r"\b(contO2?)\.(sprk|dust)\(", r"mad_\2("),
    (r"this\.xt\.carfixed\.play\(\)", "mad_fx()"),
    (r"this\.xt\.(scrape|gscrape|crash|skid)\(", "mad_fx("),
    (r"this\.rpd\.(recx|recy|recz|cotchinow)\(", "mad_fx("),
    (r"this\.rpd\.(\w+)", r"M->env->rpd_\1"),
    (r"this\.(xt|m)\.", "M->env->"),
    (r"\b(xt|m)\.(laptime|checkpoint)\b", r"M->env->\2"),
    (r"\bthis\.", "M->"),
    (r"\bcontO2\.(x|y|z|xz|xy|zy|wxz|wzy|dist)\b", r"o2->in->\1"),
    (r"\bcontO\.(x|y|z|xz|xy|zy|wxz|wzy|dist)\b", r"o->in->\1"),
    (r"\bcontO2\.", "o2->"),
    (r"\bcontO\.", "o->"),
    (r"\btrackers\.", "T->"),
    (r"\bcheckPoints\.", "cp->"),
    (r"\bcontrol\.", "ctl->"),
    (r"\bmad\.(?!reg)", "mad->"),
    (r"\bcontO2\b", "o2"),
    (r"\bcontO\b", "o"),
    (r"(T->sect\[\w+\]\[\w+\])\[(\w+)\]", r"\1.v[\2]"),
    (r"M->cd\.(\w+)\[([^\]]+)\]", r"M->cd[\2].\1"),   # CarDefine's per-stat arrays -> NFM_CARS rows
]

DROP = re.compile(r"xtGraphics xt = |Medium m = |new Color\(|hsbColor|getHSBColor|Color\.")


def translate(lines: list[str]) -> list[str]:
    out = []
    for ln in lines:
        if DROP.search(ln):
            continue
        s = ln.rstrip()
        for pat, rep in RULES:
            s = re.sub(pat, rep, s)
        out.append(s)
    return out


def main() -> None:
    p = Path(sys.argv[1] if len(sys.argv) > 1 else os.environ["NFM_SRC"] + "/Mad.java")
    src = p.read_text().splitlines()
    out = ["/* GENERATED by spec/gen_nfm_mad.py from Mad.java — do not edit. */"]
    i = 0
    while i < len(src):
        ln = src[i].strip()
        sig = next((k for k in SIGS if ln.startswith(k)), None)
        if sig is None:
            i += 1
            continue
        j = i + 1
        while src[j] != "    }":
            j += 1
        out.append(SIGS[sig])
        out += translate(src[i + 1:j])
        out.append("}\n")
        i = j + 1
    dst = Path(__file__).resolve().parent.parent / "runtime" / "nfm" / "gen" / "mad_gen.inc"
    dst.write_text("\n".join(out) + "\n")
    print(dst, len(out), "lines")


if __name__ == "__main__":
    main()
