#!/usr/bin/env python3
"""Bake docs/logo.png into runtime/game/logo_data.h (RGBA5551, 512x128 texture,
384-wide content) for the PSP boot splash. The logo is this project's own art, so
unlike the game assets it is committed and compiled straight into the binary.

    .venv/bin/python tools/make_logo_header.py
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
TEX_W, TEX_H = 512, 128
CONTENT_W = 384

img = Image.open(ROOT / "docs" / "logo.png").convert("RGBA")
ch = round(CONTENT_W * img.height / img.width)
img = img.resize((CONTENT_W, ch), Image.LANCZOS)

px = [0] * (TEX_W * TEX_H)
for y in range(ch):
    for x in range(CONTENT_W):
        r, g, b, a = img.getpixel((x, y))
        if a < 128:
            continue
        px[y * TEX_W + x] = 0x8000 | ((b >> 3) << 10) | ((g >> 3) << 5) | (r >> 3)

lines = []
for i in range(0, len(px), 16):
    lines.append("  " + ",".join("0x%04X" % v for v in px[i:i + 16]) + ",")

out = ROOT / "runtime" / "game" / "logo_data.h"
out.write_text(
    "/* generated by tools/make_logo_header.py from docs/logo.png — do not edit */\n"
    "#define LOGO_TEX_W %d\n#define LOGO_TEX_H %d\n#define LOGO_W %d\n#define LOGO_H %d\n"
    "static const unsigned short logo_px[LOGO_TEX_W * LOGO_TEX_H] = {\n%s\n};\n"
    % (TEX_W, TEX_H, CONTENT_W, ch, "\n".join(lines))
)
print("wrote %s (%dx%d content in %dx%d texture)" % (out, CONTENT_W, ch, TEX_W, TEX_H))
